ArianNovinWeb/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ArianNovinWeb.Data;
using ArianNovinWeb.Models;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using ArianNovinWeb.ViewModels;
using Microsoft.AspNetCore.Antiforgery;

namespace ArianNovinWeb.Controllers
{
    [Authorize]
    public class PostController : Controller
    {


        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        /// <summary>
        /// Constructor for the PostController class.
        /// </summary>
        /// <param name="context">ApplicationDbContext instance</param>
        /// <param name="userManager">UserManager instance</param>
        /// <param name="webHostEnvironment">WebHostEnvironment instance</param>
        public PostController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;

        }

        #region Index
        /// <summary>
        /// Displays the list of posts with the latest post displayed.
        /// </summary>
        /// <param name="id">Optional post ID</param>
        /// <returns>Index view with posts</returns>
        [AllowAnonymous]
        public async Task<IActionResult> Index(int? id)
        {
            var posts = await _context.Posts
                .Include(p => p.Author)
                .Include(p => p.Comments)
                .ThenInclude(c => c.Author)
                .ToListAsync();

            //Latest Posts Section
            var latestPosts = await _context.Posts
                .OrderByDescending(p => p.CreateDate)
                .Take(5)
                .ToListAsync();

            var latestPostsViewModel = new LatestItemsVM
            {
                Title = "Latest Posts",
                Items = latestPosts
            };
            //Latest Post

            if (!posts.Any())
            {
                var emptyViewModel = new PostIndexVM
                {
                    Posts = posts,
                    ShowShareButton = true
                };
                return View(emptyViewModel);
            }

            if (id == null)
            {
                //id = posts.First().PostId;
                id = posts.LastOrDefault().PostId;
            }

            var currentPost = posts.FirstOrDefault(p => p.PostId == id);

            if (currentPost == null)
            {
                return NotFound("Post not found.");
            }

            var currentIndex = posts.IndexOf(currentPost);
            var previousPostId = currentIndex > 0 ? posts[currentIndex - 1].PostId : (int?)null;
            var nextPostId = currentIndex < posts.Count - 1 ? posts[currentIndex + 1].PostId : (int?)null;

            var postNavigation = new PostNavigationVM
            {
                Post = currentPost,
                PreviousPostId = previousPostId,
                NextPostId = nextPostId
            };

            var populatedViewModel = new PostIndexVM
            {
                Posts = posts,
                PostNavigation = postNavigation,
                ShowShareButton = false,
                LatestPosts = latestPostsViewModel
            };

            return View(populatedViewModel);
        }
        #endregion

        #region Create
        /// <summary>
        /// Displays the Create Post form.
        /// </summary>
        /// <returns>Create view</returns>
        [Authorize]
        public IActionResult Create()
        {
            var post = new Post
            {
                AuthorId = _userManager.GetUserId(User),
                Author = _context.Users.FirstOrDefault(u => u.Id == _userManager.GetUserId(User)),
                CreateDate = DateTime.Now
            };
            return View();
        }

        /// <summary>
        /// Handles the submission of the Create Post form.
        /// </summary>
        /// <param name="post">Post model</param>
        /// <param name="imageFile">Uploaded image file</param>
        /// <returns>Redirects to Index view</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(Post post, IFormFile imageFile)
        {

            #region Uploading file
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if (imageFile != null)
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"images\");
                var extension = Path.GetExtension(imageFile.FileName);

                if (post.ImagePath != null) //deleting image if already exists
                {
                    var oldImagePath = Path.Combine(wwwRootPath, post.ImagePath.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    imageFile.CopyTo(fileStreams);
                }
                post.ImagePath = @"\images\" + fileName + extension;
            }
            #endregion

            post.CreateDate = DateTime.Now;
            post.AuthorId = _userManager.GetUserId(User);
            _context.Add(post);
            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = "Post Created Successfully";
            return RedirectToAction(nameof(Index));

        }
        #endregion

        #region Edit
        /// <summary>
        /// Displays the Edit Post form.
        /// </summary>
        /// <param name="id">Post ID</param>
        /// <returns>Edit view</returns>
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            if (post.AuthorId != userId)
            {
                return Forbid();
            }
            return View(post);
        }

        /// <summary>
        /// Handles the submission of the Edit Post form.
        /// </summary>
        /// <param name="id">Post ID</param>
        /// <param name="post">Post model</param>
        /// <param name="imageFile">Uploaded image file</param>
        /// <returns>Redirects to Index view</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, Post post, IFormFile imageFile)
        {
            var existingPost = await _context.Posts.AsNoTracking().FirstOrDefaultAsync(p => p.PostId == id);

            if (id != post.PostId)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            if (post.AuthorId != userId)
            {
                return Forbid(); // Access denied
            }
            ModelState.Remove("imageFile");
            if (ModelState.IsValid)
            {
                try
                {
                    if (imageFile != null && imageFile.Length > 0)
                    {
                        var fileName = Path.GetFileName(imageFile.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await imageFile.CopyToAsync(stream);
                        }

                        post.ImagePath = "/images/" + fileName;
                    }

                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["SuccessMessage"] = "Post Edited Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }
        #endregion

        #region Delete
        /// <summary>
        /// Displays the Delete Post confirmation view.
        /// </summary>
        /// <param name="id">Post ID</param>
        /// <returns>Delete view</returns>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Author)
                .FirstOrDefaultAsync(m => m.PostId == id);

            if (post == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            if (post.AuthorId != userId)
            {
                return Forbid();
            }

            return View(post);
        }

        /// <summary>
        /// Handles the deletion of a post and its related comments.
        /// </summary>
        /// <param name="id">Post ID</param>

ArianNovinWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ArianNovinWeb.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

[Authorize]
public class UserController : Controller
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;

    /// <summary>
    /// Constructor for the UserController class.
    /// </summary>
    /// <param name="userManager">UserManager instance</param>
    /// <param name="roleManager">RoleManager instance</param>
    public UserController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
    {
        _userManager = userManager;
        _roleManager = roleManager;
    }

    #region Edit
    /// <summary>
    /// Displays the user's profile for editing.
    /// </summary>
    /// <returns>Edit view with user details</returns>
    public async Task<IActionResult> Edit()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound();
        }

        var model = new EditUserVM
        {
            Id = user.Id,
            UserName = user.UserName,
            Email = user.Email,
            PhoneNumber = user.PhoneNumber
        };

        return View(model);
    }

    /// <summary>
    /// Updates the user's profile.
    /// </summary>
    /// <param name="model">EditUserVM instance</param>
    /// <returns>Redirects to Edit view or returns to Edit view if there is an error</returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(EditUserVM model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var user = await _userManager.FindByIdAsync(model.Id);
        if (user == null)
        {
            return NotFound();
        }

        user.UserName = model.UserName;
        user.Email = model.Email;
        user.PhoneNumber = model.PhoneNumber;
        

        var result = await _userManager.UpdateAsync(user);
        if (result.Succeeded)
        {
            TempData["SuccessMessage"] = "Your profile has been updated";
            return RedirectToAction(nameof(Edit));
        }

        foreach (var error in result.Errors)
        {
            ModelState.AddModelError(string.Empty, error.Description);
        }

        return View(model);
    }
    #endregion

    #region Check Users
    /// <summary>
    /// Displays the list of users for admin.
    /// </summary>
    /// <returns>Index view with users and their roles</returns>
    [Authorize(Roles = "Admin")]
    public IActionResult Index()
    {
        var users = _userManager.Users.Select(u => new UserVM
        {
            Id = u.Id,
            UserName = u.UserName,
            Email = u.Email,
            Roles = _userManager.GetRolesAsync(u).Result
        }).ToList();

        return View(users);
    }
    #endregion

    #region Edit User Roles
    /// <summary>
    /// Displays the edit roles form for a specific user.
    /// </summary>
    /// <param name="userId">User ID</param>
    /// <returns>EditRoles view with user roles</returns>
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> EditRoles(string userId)
    {
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null)
        {
            return NotFound();
        }

        var userRoles = await _userManager.GetRolesAsync(user);
        var allRoles = await _roleManager.Roles.Select(r => r.Name).Distinct().ToListAsync();

        var model = new EditUserRoleVM
        {
            UserId = user.Id,
            AvailableRoles = allRoles ?? new List<string>(),
            SelectedRoles = userRoles
        };

        return View(model);
    }

    /// <summary>
    /// Updates the roles of a user.
    /// </summary>
    /// <param name="model">EditUserRoleVM instance</param>
    /// <returns>Redirects to Index view or returns to EditRoles view if there is an error</returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> EditRoles(EditUserRoleVM model)
    {
        if (model.AvailableRoles == null || !model.AvailableRoles.Any())
        {
            model.AvailableRoles = await _roleManager.Roles.Select(r => r.Name).Distinct().ToListAsync();
        }

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var user = await _userManager.FindByIdAsync(model.UserId);
        if (user == null)
        {
            return NotFound();
        }

        var userRoles = await _userManager.GetRolesAsync(user);
        var rolesToAdd = model.SelectedRoles.Except(userRoles).ToList();
        var rolesToRemove = userRoles.Except(model.SelectedRoles).ToList();

        var addResult = await _userManager.AddToRolesAsync(user, rolesToAdd);
        if (!addResult.Succeeded)
        {
            foreach (var error in addResult.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(model);
        }

        var removeResult = await _userManager.RemoveFromRolesAsync(user, rolesToRemove);
        if (!removeResult.Succeeded)
        {
            foreach (var error in removeResult.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(model);
        }

        return RedirectToAction(nameof(Index));
    }
    #endregion
}

ArianNovinWeb/Views/Shared/_CommentPartial.cshtml
@model ArianNovinWeb.Models.Comment

<div class="card border-primary mb-3">
    <div class="card-body">
        <p class="card-header">
            @if (Model.Author.UserName != null)
            {
                <small class="text-black">
                    Post by @Model.Author.UserName at @Model.CreatedAt
                </small>
            }
            else
            {
                <small class="text-black">
                    Post by @Model.Author.Email at @Model.CreatedAt
                </small>
            }
        </p>
        <p class="card-text">@Model.Content</p>

        <!-- Reply form -->
        <form asp-action="AddReply" method="post" class="mt-2">
            <input type="hidden" name="PostId" value="@Model.PostId" />
            <input type="hidden" name="ParentCommentId" value="@Model.CommentId" />
            <div class="mb-2">
                <textarea name="Content" class="form-control" rows="2" placeholder="Reply..." required></textarea>
            </div>
            <button type="submit" class="btn btn-secondary btn-sm">Reply</button>
        </form>

        <!-- Render replies recursively -->
        @if (Model.Replies != null && Model.Replies.Any())
        {
            <div class="ml-4 mt-2">
                @foreach (var reply in Model.Replies)
                {
                    @await Html.PartialAsync("_CommentPartial", reply)
                }
            </div>
        }
    </div>
</div>

ArianNovinWeb/Views/Shared/_LatestItemsPartial.cshtml
@model ArianNovinWeb.ViewModels.LatestItemsVM

<div class="card mt-5 bg- ">
    <div class="card-header mb-2">
        <h3>@Model.Title</h3>
    </div>
    <ul class="list-group list-group-flush">
        @foreach (var item in Model.Items)
        {
            <li class="card bg-dark mb-2">
                <div class="card-header text-black text-bg-light bg-secondary">
                    <a class="text-black" href="@Url.Action("Index", new { id = item.PostId })">@item.Title</a>

            </div>
                <div class="card-body">
                    @if (!string.IsNullOrEmpty(item.ImagePath))
                    {
                        <img src="@item.ImagePath" alt="Item Image" class="img-thumbnail" style="width: 150px; height: auto; margin-right: 5px;">
                    }
                </div>
                <div>
                    
                </div>
            </li>
        }
    </ul>
</div>

ArianNovinWeb/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Arian Novin Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArianNovinWeb.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
@*     <meta name="csrf-token" content="@Antiforgery.GetAndStoreTokens(Context).RequestToken" />
 *@

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Post" asp-action="Index">
                                Post
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Course" asp-action="Index">
                                Course
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://github.com/Hr-Panahi/ArianNovinProj" target="_blank">GitHub</a>
                        </li>
                    </ul>
                </div>
                <div class="mx-auto order-0">
                    <a class="navbar-brand mx-auto" asp-area="" asp-controller="Home" asp-action="Index">ArianNovinWeb</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ms-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item text-white">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Edit">Edit Profile</a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                </li>
                            }
                            <li class="nav-item">
                                <form method="post" asp-area="Identity" asp-page="/Account/Logout" id="logoutForm" class="form-inline">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item bg-white">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                            <li class="nav-item bg-white">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @*
    <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2024 - ArianNovinWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>